### ISSUE TITLE
[Enhancement]Function to allow scanning memory from an arbitrary base address

### ISSUE THREAD

**Issue by jfmherokiller** [D3l0ry/NativeManager#1]
I added a function to PatternManager to allow scanning memory from a user defined base address and search size.

```
        public IntPtr FindPatternCBase(IntPtr modulePtr, byte[] pattern, int searchSize = 5000)
        {
            if (pattern == null)
            {
                return IntPtr.Zero;
            }
            var searchme = 0;
            for (long PIndex = modulePtr.ToInt64(); searchme < searchSize; PIndex++)
            {
                bool Found = true;

                for (int MIndex = 0; MIndex < pattern.Length; MIndex++)
                {
                    Found = pattern[MIndex] == 0 || m_MemoryManager.Read<byte>((IntPtr)(PIndex + MIndex)) == pattern[MIndex];

                    if (!Found)
                    {
                        break;
                    }
                }

                searchme++;
                if (Found)
                {
                    return (IntPtr)(PIndex);
                }
            }

            return IntPtr.Zero;
        }
```
Im not adding it as a pull request because I dont think my code is to your specs.

**Comment by D3l0ry** [comment]
Yes, this will be considered a useful function, but in rare cases when you know that in the interval from the base address to the base address + 5000 you will find the code you need. Sorry for my bad English.

**Comment by jfmherokiller** [comment]
Its ok the idea behind it is for unreal engine signature scanning where in you can get close to your value you desire but you don't know exactly where it is.

**Comment by D3l0ry** [comment]
I think that I will improve the already prepared function to resize the search. Thanks for the idea, it can really help in the future.
