### ISSUE TITLE
[Enhancement]Get A list of all memory pages

### ISSUE THREAD

**Issue by jfmherokiller** [D3l0ry/NativeManager#2]
I dont know if you added something like this already but have my function i added for getting all pages allocated to a current process.

```
        public MEMORY_BASIC_INFORMATION[] GetAllPages()
        {
            List<MEMORY_BASIC_INFORMATION> pages = new List<MEMORY_BASIC_INFORMATION>(10);
            SYSTEM_INFO systemInfo = GetSystemInfo();
            Directory.EnumerateFiles(".");
            byte* startAddress = (byte*)systemInfo.lpMinimumApplicationAddress.ToPointer();
            byte* maximumAddress = (byte*)systemInfo.lpMaximumApplicationAddress.ToPointer();

            while (startAddress < maximumAddress)
            {
                var thepage = GetPage((IntPtr) startAddress);
                if (thepage.State == (int) StateType.MEM_COMMIT)
                {
                    pages.Add(thepage);
                }
                startAddress += thepage.RegionSize;
            }

            return pages.ToArray();
        }
```

**Comment by jfmherokiller** [comment]
i basicly use the StateType check to remove any pages which arent part of the process memory space.

Also making use of RegionSize is much better because you could easily end up with duplicates otherwise.

**Comment by D3l0ry** [comment]
Thanks for the contribution, I took into account your comment.  I will make corrections in the code.  I have a similar function, but it starts from the specified address, and yours from the beginning of the process memory, so I will update the PageManager class soon.

**Comment by D3l0ry** [comment]
I believe that using MEM_COMIT is not always useful when searching for pages, because sometimes we need to find areas that will be free for future memory allocation.  So it might be worth checking what exactly you need to look for.

**Comment by jfmherokiller** [comment]
Oh true i didnt think of that I was mostly trying to avoid array overflows.
